# resource_group_name_dev      = "mtc-resource-group-dev"
# resource_group_name_test     = "mtc-resource-group-test"
# resource_group_name_prod     = "mtc-resource-group-prod"
azurerm_provider_version     = "3.23.0"
location                     = "westeurope"