resource_group_name    = "mtc_terraform_keyvault_rbac_rg"
location               = "West Europe"
keyvault_name          = "mtc-demo-keyvault02"
secret_name            = "dbpasswordexample"
secret_value           = "Password1234!@"